services:
  postgres_1:
    image: postgres:14-alpine
    container_name: postgres_1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1337
      POSTGRES_DB: service_1
    volumes:
      - postgres_data_1:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  postgres_2:
    image: postgres:14-alpine
    container_name: postgres_2
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1337
      POSTGRES_DB: service_2
    volumes:
      - postgres_data_2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  service_1:
    build:
      context: ./service_1
      dockerfile: Dockerfile
    container_name: service_1
    ports:
      - 8080:8080
    depends_on:
      postgres_1:
        condition: service_healthy

  service_2:
    build:
      context: ./service_2
      dockerfile: Dockerfile
    container_name: service_2
    ports:
      - 8081:8081
    depends_on:
      postgres_2:
        condition: service_healthy

volumes:
  postgres_data_1:
  postgres_data_2:
